name: CI
run-name: >
  ${{ github.workflow }}
  ${{ github.event_name == 'pull_request' &&
      format(' - {0} (#{1})', github.event.pull_request.title, github.event.pull_request.number) || '' }}
concurrency:
  # This section ensure that multiple PR pushes will cancel superseded builds.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    # When a PR is to be merged to the main branch or any release branches
    branches:
      - "main"
      - "release/**"

  push:
    # When the main branch or any release branch is updated
    branches:
      - "main"
      - "release/**"

  workflow_dispatch:

jobs:
  CI:
    name: Format, Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Formater and linter check
        run: yarn checker

      - name: Build
        run: yarn build
