name: CI
run-name: >
  ${{ github.workflow }}
  ${{ github.event_name == 'pull_request' &&
      format(' - {0} (#{1})', github.event.pull_request.title, github.event.pull_request.number) || '' }}
  ${{ github.event_name == 'push' && format(' - {0}', github.ref_name) || '' }}
concurrency:
  # This section ensure that multiple PR pushes will not cancel superseded builds.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  pull_request:
    # When a PR is to be merged to the main branch or any release branches
    branches:
      - 'main'
      - 'release/**'

  push:
    # When the main branch or any release branch is updated
    branches:
      - 'main'
      - 'release/**'

  workflow_dispatch:

jobs:
  CI:
    name: Format, Lint and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: >
          yarn

      - name: Format check
        shell: bash
        run: >
          yarn format:check

      - name: Lint check
        shell: bash
        run: >
          yarn lint

      - name: Build
        shell: bash
        run: >
          yarn build
